# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "24912e424a44ae220c00e7e2a070273f"
name = "Cellexia-page-tailor"
application_url = "https://cellexia-page-tailor.onrender.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[webhooks]
api_version = "2026-10"

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/scopes_update"
  topics = [ "app/scopes_update" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/uninstalled"
  topics = [ "app/uninstalled" ]

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,read_translations,read_locales,read_orders"

[auth]
redirect_urls = [ "https://cellexia-page-tailor.onrender.com/auth/callback" ]

[app_proxy]
url = "https://cellexia-page-tailor.onrender.com/proxy"
subpath = "cx"
prefix = "apps"
