# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "7a4e286102ecaa26f2cf018176cb9fd1"
name = "cellexia-page-tailor"
application_url = "https://example.com"
embedded = true

[webhooks]
api_version = "2026-10"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [ "https://example.com/api/auth" ]

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true
